coverage:
  status:
    project:
      default:
        target: 95%
        threshold: 1%
        paths:
          - "src/*"
    patch:
      default:
        target: 95%
        threshold: 1%
        paths:
          - "src/*"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  require_changes: true
  require_base: yes
