comment:
  layout: reach,diff,flags,files,footer
  require_base: true
  require_changes: true

coverage:
  status:
    patch:
      default:
        paths:
          - (?s:src/[^\/]*)\Z
        target: 95.0
        threshold: 1.0
    project:
      default:
        paths:
          - (?s:src/[^\/]*)\Z
        target: 95.0
        threshold: 1.0
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
